3-First
EdenHuang2056/taipei-day-trip-website pull request #4
Opened 2021-05-30 12:38 UTC by EdenHuang2056

老師～～有空可以幫我看一下第三週的部分嗎？謝謝～～

黃宏裕
http://50.18.127.34:3000/
http://50.18.127.34:3000/attractions/220

2021-05-30 13:55 UTC, EdenHuang2056 commented
老師，我發現有些問題，我處理好再跟你說，謝謝～

2021-05-30 14:37 UTC, EdenHuang2056 commented
老師，我修改好了，再麻煩幫我確認一下，感謝～

2021-05-30 17:28 UTC, cwpeng requested changes
需要你把版面細節在處理得更仔細一些：
1. 景點上方和下方的文字介紹間有一條水平線。
2. 開始預定行程的按鈕文字顏色，對齊顯然和設計稿不同。
3. 訂購導覽行程的灰色框框和內部的文字間有一些距離，不會黏得緊緊的。

2021-05-31 01:13 UTC, EdenHuang2056 commented
老師～我修改好了，再麻煩幫我看一下，謝謝。

2021-05-31 01:18 UTC, cwpeng commented
請重新發 Review Request 給我 ~

2021-05-31 01:20 UTC, cwpeng approved these changes
OK.

2021-05-31 01:20 UTC, EdenHuang2056 commented
好了～

2021-05-31 01:20 UTC, EdenHuang2056 commented
感謝老師！！！

2021-05-31 01:20 UTC, merged