week4
EdenHuang2056/taipei-day-trip-website pull request #5
Opened 2021-06-04 10:51 UTC by EdenHuang2056

老師～～麻煩有空幫我看一下週四的內容，謝謝～～～

黃宏裕
http://50.18.127.34:3000/
http://50.18.127.34:3000/attractions/220

2021-06-04 18:45 UTC, cwpeng requested changes
有幾個嚴重的問題需要修正哦：
1. 註冊冊之後，畫面不能跳到一個使用者看不懂的東西。連線用 AJAX 在背景執行，成功或失敗要顯示在對話框中，畫面不會跳到另一頁。
2. 按登入雖然顯示成功，但只要重新整理頁面或到另外一個頁面都無法保持登入狀態。

2021-06-05 10:00 UTC, EdenHuang2056 commented
老師～～我修改好了，在麻煩幫我看一下，感恩～～

2021-06-05 23:38 UTC, cwpeng approved these changes
OK.

2021-06-06 00:40 UTC, EdenHuang2056 commented
謝謝老師！！

2021-06-06 00:41 UTC, merged